title: Kishan Patel 
description: Blogs about computer science, finance, and fitness 
show_downloads: true
google_analytics:
theme: jekyll-theme-merlot
markdown: kramdown 
plugins: ['jekyll-plantuml']
