# Site settings
title: patelkishan.com 
email: kishan@patelkishan.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.patelkishan.com" # the base hostname & protocol for your site
github_username: kishan-patel 
theme: jekyll-theme-merlot

# Build settings
markdown: kramdown

gems: ['jekyll-plantuml']
